services:
  postgres:
   container_name: postgres
   image: postgres
   restart: always
   environment:
    POSTGRES_DB: pet_project
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
   ports:
    - 5435:5432
   volumes:
    - postgres-data:/var/lib/postgressql/data
  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
        - ACCEPT_EULA=Y
    ports:
        - 5341:5341
        - 8081:80
  minio:
    container_name: minio
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data
    command: server --console-address ":9001" /data
    restart: always
volumes:
   postgres-data:
   minio-data:
   
