services:
  postgres:
   container_name: postgres
   image: postgres
   restart: always
   environment:
    POSTGRES_DB: pet_project
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
   ports:
    - 5435:5432
   volumes:
    - postgres-data:/var/lib/postgressql/data

volumes:
   postgres-data:
   
